# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Pypi Install
      run: |
        python -m pip install --upgrade pip

    - name: Pypi Install
      run: |
          python -m pip install --upgrade pip

    - name: dependencies Install
      run: |
        pip install -r requirements.txt
    - name: pyinstaller package exe
      run: |
        pyinstaller --noconfirm --onedir --console --name "xxt" --add-data "./new_xxt/LICENSE;." --add-data "./new_xxt/README.md;." --add-data "./new_xxt/user.json;." --add-data "./new_xxt/answers;answers/"  "./new_xxt/main.py"
        
